INSERT INTO report_realm VALUES(NULL, 'Aegwynn', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Aerie Peak', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Agamaggan', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Aggramar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Akama', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Alexstrasza', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Alleria', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Altar of Storms', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Alterac Mountains', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Aman''Thul', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Andorhal', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Anetheron', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Antonidas', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Anub''arak', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Anvilmar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Arathor', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Archimonde', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Area 52', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Argent Dawn', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Arthas', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Arygos', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Auchindoun', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Azgalor', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Azjol-Nerub', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Azshara', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Azuremyst', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Baelgun', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Balnazzar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Barthilas', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Black Dragonflight', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Blackhand', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Blackrock', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Blackwater Raiders', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Blackwing Lair', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Blade''s Edge', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Bladefist', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Bleeding Hollow', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Blood Furnace', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Bloodhoof', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Bloodscalp', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Bonechewer', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Boulderfist', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Bronzebeard', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Burning Blade', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Burning Legion', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Cenarion Circle', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Cenarius', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Cho''gall', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Chromaggus', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Coilfang', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Crushridge', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Daggerspine', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Dalaran', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Dalvengyr', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Dark Iron', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Darkspear', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Darrowmere', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Dath''Remar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Deathwing', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Demon Soul', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Dentarg', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Destromath', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Dethecus', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Detheroc', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Doomhammer', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Draenor', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Dragonblight', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Dragonmaw', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Drak''thul', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Draka', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Drenden', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Dunemaul', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Durotan', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Duskwood', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Earthen Ring', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Echo Isles', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Eitrigg', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Eldre''Thalas', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Elune', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Emerald Dream', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Eonar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Eredar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Executus', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Exodar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Farstriders', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Feathermoon', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Fenris', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Firetree', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Frostmane', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Frostmourne', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Frostwolf', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Garithos', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Garona', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Gilneas', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Gnomeregan', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Gorefiend', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Gorgonnash', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Greymane', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Gul''dan', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Gurubashi', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Hakkar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Haomarush', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Hellscream', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Hydraxis', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Hyjal', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Icecrown', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Illidan', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Jaedenar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Jubei''Thos', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Kael''thas', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Kalecgos', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Kargath', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Kel''Thuzad', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Khadgar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Khaz Modan', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Khaz''goroth', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Kil''Jaeden', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Kilrogg', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Kirin Tor', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Korgath', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Korialstrasz', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Kul Tiras', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Laughing Skull', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Lethon', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Lightbringer', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Lightning''s Blade', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Lightninghoof', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Llane', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Lothar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Madoran', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Maelstrom', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Magtheridon', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Maiev', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Mal''Ganis', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Malfurion', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Malorne', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Malygos', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Mannoroth', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Medivh', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Misha', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Mok''Nathal', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Moon Guard', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Moonrunner', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Mug''thol', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Muradin', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Nagrand', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Nathrezim', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Nazgrel', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Nazjatar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Ner''zhul', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Nordrassil', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Norgannon', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Onyxia', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Perenolde', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Proudmoore', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Quel''dorei', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Ravencrest', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Ravenholdt', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Rexxar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Rivendare', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Runetotem', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Sargeras', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Scarlet Crusade', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Scilla', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Sen''Jin', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Sentinels', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Shadow Council', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Shadowmoon', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Shadowsong', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Shandris', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Shattered Halls', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Shattered Hand', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Shu''halo', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Silver Hand', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Silvermoon', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Sisters of Elune', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Skullcrusher', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Skywall', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Smolderthorn', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Spinebreaker', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Spirestone', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Staghelm', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Steamwheedle Cartel', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Stonemaul', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Stormrage', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Stormreaver', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Stormscale', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Suramar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Tanaris', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Terenas', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Terokkar', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Thaurissan', 'EU');
INSERT INTO report_realm VALUES(NULL, 'The Forgotten Coast', 'EU');
INSERT INTO report_realm VALUES(NULL, 'The Scryers', 'EU');
INSERT INTO report_realm VALUES(NULL, 'The Underbog', 'EU');
INSERT INTO report_realm VALUES(NULL, 'The Venture Co', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Thorium Brotherhood', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Thrall', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Thunderhorn', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Thunderlord', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Tichondrius', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Tortheldrin', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Trollbane', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Turalyon', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Twisting Nether', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Uldaman', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Uldum', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Undermine', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Ursin', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Uther', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Vashj', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Vek''nilash', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Velen', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Warsong', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Whisperwind', 'EU');
INSERT INTO report_realm VALUES(NULL, 'WildHammer', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Windrunner', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Ysera', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Ysondre', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Zangarmarsh', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Zul''jin', 'EU');
INSERT INTO report_realm VALUES(NULL, 'Zuluhed', 'EU');