INSERT INTO report_realm VALUES(NULL, 'Aegwynn', 'US');
INSERT INTO report_realm VALUES(NULL, 'Aerie Peak', 'US');
INSERT INTO report_realm VALUES(NULL, 'Agamaggan', 'US');
INSERT INTO report_realm VALUES(NULL, 'Aggramar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Akama', 'US');
INSERT INTO report_realm VALUES(NULL, 'Alexstrasza', 'US');
INSERT INTO report_realm VALUES(NULL, 'Alleria', 'US');
INSERT INTO report_realm VALUES(NULL, 'Altar of Storms', 'US');
INSERT INTO report_realm VALUES(NULL, 'Alterac Mountains', 'US');
INSERT INTO report_realm VALUES(NULL, 'Aman''Thul', 'US');
INSERT INTO report_realm VALUES(NULL, 'Andorhal', 'US');
INSERT INTO report_realm VALUES(NULL, 'Anetheron', 'US');
INSERT INTO report_realm VALUES(NULL, 'Antonidas', 'US');
INSERT INTO report_realm VALUES(NULL, 'Anub''arak', 'US');
INSERT INTO report_realm VALUES(NULL, 'Anvilmar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Arathor', 'US');
INSERT INTO report_realm VALUES(NULL, 'Archimonde', 'US');
INSERT INTO report_realm VALUES(NULL, 'Area 52', 'US');
INSERT INTO report_realm VALUES(NULL, 'Argent Dawn', 'US');
INSERT INTO report_realm VALUES(NULL, 'Arthas', 'US');
INSERT INTO report_realm VALUES(NULL, 'Arygos', 'US');
INSERT INTO report_realm VALUES(NULL, 'Auchindoun', 'US');
INSERT INTO report_realm VALUES(NULL, 'Azgalor', 'US');
INSERT INTO report_realm VALUES(NULL, 'Azjol-Nerub', 'US');
INSERT INTO report_realm VALUES(NULL, 'Azshara', 'US');
INSERT INTO report_realm VALUES(NULL, 'Azuremyst', 'US');
INSERT INTO report_realm VALUES(NULL, 'Baelgun', 'US');
INSERT INTO report_realm VALUES(NULL, 'Balnazzar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Barthilas', 'US');
INSERT INTO report_realm VALUES(NULL, 'Black Dragonflight', 'US');
INSERT INTO report_realm VALUES(NULL, 'Blackhand', 'US');
INSERT INTO report_realm VALUES(NULL, 'Blackrock', 'US');
INSERT INTO report_realm VALUES(NULL, 'Blackwater Raiders', 'US');
INSERT INTO report_realm VALUES(NULL, 'Blackwing Lair', 'US');
INSERT INTO report_realm VALUES(NULL, 'Blade''s Edge', 'US');
INSERT INTO report_realm VALUES(NULL, 'Bladefist', 'US');
INSERT INTO report_realm VALUES(NULL, 'Bleeding Hollow', 'US');
INSERT INTO report_realm VALUES(NULL, 'Blood Furnace', 'US');
INSERT INTO report_realm VALUES(NULL, 'Bloodhoof', 'US');
INSERT INTO report_realm VALUES(NULL, 'Bloodscalp', 'US');
INSERT INTO report_realm VALUES(NULL, 'Bonechewer', 'US');
INSERT INTO report_realm VALUES(NULL, 'Boulderfist', 'US');
INSERT INTO report_realm VALUES(NULL, 'Bronzebeard', 'US');
INSERT INTO report_realm VALUES(NULL, 'Burning Blade', 'US');
INSERT INTO report_realm VALUES(NULL, 'Burning Legion', 'US');
INSERT INTO report_realm VALUES(NULL, 'Cenarion Circle', 'US');
INSERT INTO report_realm VALUES(NULL, 'Cenarius', 'US');
INSERT INTO report_realm VALUES(NULL, 'Cho''gall', 'US');
INSERT INTO report_realm VALUES(NULL, 'Chromaggus', 'US');
INSERT INTO report_realm VALUES(NULL, 'Coilfang', 'US');
INSERT INTO report_realm VALUES(NULL, 'Crushridge', 'US');
INSERT INTO report_realm VALUES(NULL, 'Daggerspine', 'US');
INSERT INTO report_realm VALUES(NULL, 'Dalaran', 'US');
INSERT INTO report_realm VALUES(NULL, 'Dalvengyr', 'US');
INSERT INTO report_realm VALUES(NULL, 'Dark Iron', 'US');
INSERT INTO report_realm VALUES(NULL, 'Darkspear', 'US');
INSERT INTO report_realm VALUES(NULL, 'Darrowmere', 'US');
INSERT INTO report_realm VALUES(NULL, 'Dath''Remar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Deathwing', 'US');
INSERT INTO report_realm VALUES(NULL, 'Demon Soul', 'US');
INSERT INTO report_realm VALUES(NULL, 'Dentarg', 'US');
INSERT INTO report_realm VALUES(NULL, 'Destromath', 'US');
INSERT INTO report_realm VALUES(NULL, 'Dethecus', 'US');
INSERT INTO report_realm VALUES(NULL, 'Detheroc', 'US');
INSERT INTO report_realm VALUES(NULL, 'Doomhammer', 'US');
INSERT INTO report_realm VALUES(NULL, 'Draenor', 'US');
INSERT INTO report_realm VALUES(NULL, 'Dragonblight', 'US');
INSERT INTO report_realm VALUES(NULL, 'Dragonmaw', 'US');
INSERT INTO report_realm VALUES(NULL, 'Drak''thul', 'US');
INSERT INTO report_realm VALUES(NULL, 'Draka', 'US');
INSERT INTO report_realm VALUES(NULL, 'Drenden', 'US');
INSERT INTO report_realm VALUES(NULL, 'Dunemaul', 'US');
INSERT INTO report_realm VALUES(NULL, 'Durotan', 'US');
INSERT INTO report_realm VALUES(NULL, 'Duskwood', 'US');
INSERT INTO report_realm VALUES(NULL, 'Earthen Ring', 'US');
INSERT INTO report_realm VALUES(NULL, 'Echo Isles', 'US');
INSERT INTO report_realm VALUES(NULL, 'Eitrigg', 'US');
INSERT INTO report_realm VALUES(NULL, 'Eldre''Thalas', 'US');
INSERT INTO report_realm VALUES(NULL, 'Elune', 'US');
INSERT INTO report_realm VALUES(NULL, 'Emerald Dream', 'US');
INSERT INTO report_realm VALUES(NULL, 'Eonar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Eredar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Executus', 'US');
INSERT INTO report_realm VALUES(NULL, 'Exodar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Farstriders', 'US');
INSERT INTO report_realm VALUES(NULL, 'Feathermoon', 'US');
INSERT INTO report_realm VALUES(NULL, 'Fenris', 'US');
INSERT INTO report_realm VALUES(NULL, 'Firetree', 'US');
INSERT INTO report_realm VALUES(NULL, 'Frostmane', 'US');
INSERT INTO report_realm VALUES(NULL, 'Frostmourne', 'US');
INSERT INTO report_realm VALUES(NULL, 'Frostwolf', 'US');
INSERT INTO report_realm VALUES(NULL, 'Garithos', 'US');
INSERT INTO report_realm VALUES(NULL, 'Garona', 'US');
INSERT INTO report_realm VALUES(NULL, 'Gilneas', 'US');
INSERT INTO report_realm VALUES(NULL, 'Gnomeregan', 'US');
INSERT INTO report_realm VALUES(NULL, 'Gorefiend', 'US');
INSERT INTO report_realm VALUES(NULL, 'Gorgonnash', 'US');
INSERT INTO report_realm VALUES(NULL, 'Greymane', 'US');
INSERT INTO report_realm VALUES(NULL, 'Gul''dan', 'US');
INSERT INTO report_realm VALUES(NULL, 'Gurubashi', 'US');
INSERT INTO report_realm VALUES(NULL, 'Hakkar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Haomarush', 'US');
INSERT INTO report_realm VALUES(NULL, 'Hellscream', 'US');
INSERT INTO report_realm VALUES(NULL, 'Hydraxis', 'US');
INSERT INTO report_realm VALUES(NULL, 'Hyjal', 'US');
INSERT INTO report_realm VALUES(NULL, 'Icecrown', 'US');
INSERT INTO report_realm VALUES(NULL, 'Illidan', 'US');
INSERT INTO report_realm VALUES(NULL, 'Jaedenar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Jubei''Thos', 'US');
INSERT INTO report_realm VALUES(NULL, 'Kael''thas', 'US');
INSERT INTO report_realm VALUES(NULL, 'Kalecgos', 'US');
INSERT INTO report_realm VALUES(NULL, 'Kargath', 'US');
INSERT INTO report_realm VALUES(NULL, 'Kel''Thuzad', 'US');
INSERT INTO report_realm VALUES(NULL, 'Khadgar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Khaz Modan', 'US');
INSERT INTO report_realm VALUES(NULL, 'Khaz''goroth', 'US');
INSERT INTO report_realm VALUES(NULL, 'Kil''Jaeden', 'US');
INSERT INTO report_realm VALUES(NULL, 'Kilrogg', 'US');
INSERT INTO report_realm VALUES(NULL, 'Kirin Tor', 'US');
INSERT INTO report_realm VALUES(NULL, 'Korgath', 'US');
INSERT INTO report_realm VALUES(NULL, 'Korialstrasz', 'US');
INSERT INTO report_realm VALUES(NULL, 'Kul Tiras', 'US');
INSERT INTO report_realm VALUES(NULL, 'Laughing Skull', 'US');
INSERT INTO report_realm VALUES(NULL, 'Lethon', 'US');
INSERT INTO report_realm VALUES(NULL, 'Lightbringer', 'US');
INSERT INTO report_realm VALUES(NULL, 'Lightning''s Blade', 'US');
INSERT INTO report_realm VALUES(NULL, 'Lightninghoof', 'US');
INSERT INTO report_realm VALUES(NULL, 'Llane', 'US');
INSERT INTO report_realm VALUES(NULL, 'Lothar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Madoran', 'US');
INSERT INTO report_realm VALUES(NULL, 'Maelstrom', 'US');
INSERT INTO report_realm VALUES(NULL, 'Magtheridon', 'US');
INSERT INTO report_realm VALUES(NULL, 'Maiev', 'US');
INSERT INTO report_realm VALUES(NULL, 'Mal''Ganis', 'US');
INSERT INTO report_realm VALUES(NULL, 'Malfurion', 'US');
INSERT INTO report_realm VALUES(NULL, 'Malorne', 'US');
INSERT INTO report_realm VALUES(NULL, 'Malygos', 'US');
INSERT INTO report_realm VALUES(NULL, 'Mannoroth', 'US');
INSERT INTO report_realm VALUES(NULL, 'Medivh', 'US');
INSERT INTO report_realm VALUES(NULL, 'Misha', 'US');
INSERT INTO report_realm VALUES(NULL, 'Mok''Nathal', 'US');
INSERT INTO report_realm VALUES(NULL, 'Moon Guard', 'US');
INSERT INTO report_realm VALUES(NULL, 'Moonrunner', 'US');
INSERT INTO report_realm VALUES(NULL, 'Mug''thol', 'US');
INSERT INTO report_realm VALUES(NULL, 'Muradin', 'US');
INSERT INTO report_realm VALUES(NULL, 'Nagrand', 'US');
INSERT INTO report_realm VALUES(NULL, 'Nathrezim', 'US');
INSERT INTO report_realm VALUES(NULL, 'Nazgrel', 'US');
INSERT INTO report_realm VALUES(NULL, 'Nazjatar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Ner''zhul', 'US');
INSERT INTO report_realm VALUES(NULL, 'Nordrassil', 'US');
INSERT INTO report_realm VALUES(NULL, 'Norgannon', 'US');
INSERT INTO report_realm VALUES(NULL, 'Onyxia', 'US');
INSERT INTO report_realm VALUES(NULL, 'Perenolde', 'US');
INSERT INTO report_realm VALUES(NULL, 'Proudmoore', 'US');
INSERT INTO report_realm VALUES(NULL, 'Quel''dorei', 'US');
INSERT INTO report_realm VALUES(NULL, 'Ravencrest', 'US');
INSERT INTO report_realm VALUES(NULL, 'Ravenholdt', 'US');
INSERT INTO report_realm VALUES(NULL, 'Rexxar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Rivendare', 'US');
INSERT INTO report_realm VALUES(NULL, 'Runetotem', 'US');
INSERT INTO report_realm VALUES(NULL, 'Sargeras', 'US');
INSERT INTO report_realm VALUES(NULL, 'Scarlet Crusade', 'US');
INSERT INTO report_realm VALUES(NULL, 'Scilla', 'US');
INSERT INTO report_realm VALUES(NULL, 'Sen''Jin', 'US');
INSERT INTO report_realm VALUES(NULL, 'Sentinels', 'US');
INSERT INTO report_realm VALUES(NULL, 'Shadow Council', 'US');
INSERT INTO report_realm VALUES(NULL, 'Shadowmoon', 'US');
INSERT INTO report_realm VALUES(NULL, 'Shadowsong', 'US');
INSERT INTO report_realm VALUES(NULL, 'Shandris', 'US');
INSERT INTO report_realm VALUES(NULL, 'Shattered Halls', 'US');
INSERT INTO report_realm VALUES(NULL, 'Shattered Hand', 'US');
INSERT INTO report_realm VALUES(NULL, 'Shu''halo', 'US');
INSERT INTO report_realm VALUES(NULL, 'Silver Hand', 'US');
INSERT INTO report_realm VALUES(NULL, 'Silvermoon', 'US');
INSERT INTO report_realm VALUES(NULL, 'Sisters of Elune', 'US');
INSERT INTO report_realm VALUES(NULL, 'Skullcrusher', 'US');
INSERT INTO report_realm VALUES(NULL, 'Skywall', 'US');
INSERT INTO report_realm VALUES(NULL, 'Smolderthorn', 'US');
INSERT INTO report_realm VALUES(NULL, 'Spinebreaker', 'US');
INSERT INTO report_realm VALUES(NULL, 'Spirestone', 'US');
INSERT INTO report_realm VALUES(NULL, 'Staghelm', 'US');
INSERT INTO report_realm VALUES(NULL, 'Steamwheedle Cartel', 'US');
INSERT INTO report_realm VALUES(NULL, 'Stonemaul', 'US');
INSERT INTO report_realm VALUES(NULL, 'Stormrage', 'US');
INSERT INTO report_realm VALUES(NULL, 'Stormreaver', 'US');
INSERT INTO report_realm VALUES(NULL, 'Stormscale', 'US');
INSERT INTO report_realm VALUES(NULL, 'Suramar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Tanaris', 'US');
INSERT INTO report_realm VALUES(NULL, 'Terenas', 'US');
INSERT INTO report_realm VALUES(NULL, 'Terokkar', 'US');
INSERT INTO report_realm VALUES(NULL, 'Thaurissan', 'US');
INSERT INTO report_realm VALUES(NULL, 'The Forgotten Coast', 'US');
INSERT INTO report_realm VALUES(NULL, 'The Scryers', 'US');
INSERT INTO report_realm VALUES(NULL, 'The Underbog', 'US');
INSERT INTO report_realm VALUES(NULL, 'The Venture Co', 'US');
INSERT INTO report_realm VALUES(NULL, 'Thorium Brotherhood', 'US');
INSERT INTO report_realm VALUES(NULL, 'Thrall', 'US');
INSERT INTO report_realm VALUES(NULL, 'Thunderhorn', 'US');
INSERT INTO report_realm VALUES(NULL, 'Thunderlord', 'US');
INSERT INTO report_realm VALUES(NULL, 'Tichondrius', 'US');
INSERT INTO report_realm VALUES(NULL, 'Tortheldrin', 'US');
INSERT INTO report_realm VALUES(NULL, 'Trollbane', 'US');
INSERT INTO report_realm VALUES(NULL, 'Turalyon', 'US');
INSERT INTO report_realm VALUES(NULL, 'Twisting Nether', 'US');
INSERT INTO report_realm VALUES(NULL, 'Uldaman', 'US');
INSERT INTO report_realm VALUES(NULL, 'Uldum', 'US');
INSERT INTO report_realm VALUES(NULL, 'Undermine', 'US');
INSERT INTO report_realm VALUES(NULL, 'Ursin', 'US');
INSERT INTO report_realm VALUES(NULL, 'Uther', 'US');
INSERT INTO report_realm VALUES(NULL, 'Vashj', 'US');
INSERT INTO report_realm VALUES(NULL, 'Vek''nilash', 'US');
INSERT INTO report_realm VALUES(NULL, 'Velen', 'US');
INSERT INTO report_realm VALUES(NULL, 'Warsong', 'US');
INSERT INTO report_realm VALUES(NULL, 'Whisperwind', 'US');
INSERT INTO report_realm VALUES(NULL, 'WildHammer', 'US');
INSERT INTO report_realm VALUES(NULL, 'Windrunner', 'US');
INSERT INTO report_realm VALUES(NULL, 'Ysera', 'US');
INSERT INTO report_realm VALUES(NULL, 'Ysondre', 'US');
INSERT INTO report_realm VALUES(NULL, 'Zangarmarsh', 'US');
INSERT INTO report_realm VALUES(NULL, 'Zul''jin', 'US');
INSERT INTO report_realm VALUES(NULL, 'Zuluhed', 'US');